#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    screen_name = sys.argv[1]

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    

    #queries Twitter's API to return a list of a user's most recent 50 tweets
    list_tweets = get_user_timeline(screen_name[1:], 50)
    
    #debug
    #print (list_tweets, file=open("listtweets.txt", "w"))
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
        # analyze tweets
        #iterate over the list of tweets and extract each tweet
    for tweet in list_tweets:
        score = analyzer.analyze(tweet)
        
        #prepare colored print output format
        score_tweet_user = str(score) + " " + tweet + screen_name
    
        #print depending on tweet sentiment
        if score > 0.0:
            print(colored(score_tweet_user, "green")) 
        elif score < 0.0:
            print(colored(score_tweet_user, "red"))
        else:
            print(colored(score_tweet_user, "yellow"))

if __name__ == "__main__":
    main()